// This file is automatically generated. Do not edit it directly.
// REPLACED WITH MOCK DB FOR LOCAL DEVELOPMENT
import { mockDB } from '@/services/mock-db';

// Exporting mockDB as 'supabase' to minimize refactoring across the app
export const supabase = mockDB as any;